### ISSUE TITLE
Move non-ESDK functionality out

### ISSUE THREAD

**Issue by 9600** [DesignSparkRS/DesignSpark.ESDK#2]
This issue may need splitting into multiple. E.g. this shouldn't:

* Load an application-specific config file (configFile='/boot/aq/aq.toml'). The app should be loading this instead.
* Take care of geohash, which is again app-specific.
* Be concerned with MQTT or Prometheus.

Should consider whether there is merit in having a new "cloud" or "data" module to wrap things like MQTT, Prometheus and maybe even data formatting such as geohash.

**Comment by callumsnowden** [comment]
Separated out the configuration bits so that a MQTT, Prometheus etc is in the AQ firmware, and a configuration dictionary has to be passed in instead now.

Need to finish separating out GPS configuration & location providing to return lat/lon.

**Comment by callumsnowden** [comment]
Fixed in https://github.com/DesignSparkRS/DesignSpark.ESDK/commit/4cdeec945bd7651234923987ff3c331c55c090f0
